In [ ]:
# !conda create -n skmob python=3.9.0
# !conda install conda-forge scikit-mobility

In [1]:
import networkx as nx
import pandas as pd # version 2.3.1
import geopandas as gpd #1.0.1
import numpy as np # 2.2.6
import shapely   # 2.0.7 , measure importance of features through SHAP values
import skmob

Cannot find header.dxf (GDAL_DATA is not defined)

In [2]:
import os

data_folder = "data/2017-2021"
# datasets is aggregated commuter trajectories
datasets = {}

for filename in os.listdir(data_folder):
    # filename.split("_") creates list of items split from the filename -> [-1] access last item -> .split(".") splits last item by "."-> [0] accesses the first item which is the state code
    state_code = filename.split("_")[-1].split(".")[0]
    file_path = os.path.join(data_folder, filename)
    df = pd.read_csv(file_path)
    # Add the DataFrame to the container with the state code as the label
    datasets[state_code] = df

In [33]:
datasets['FL'].groupby("Otract").nunique()

             Dtract  EST
Otract
12001000201      24   15
12001000202      28   15
12001000301      27   19
12001000302      27   13
12001000400      28   16
...             ...  ...
12133970104      14   10
12133970200      27   10
12133970301      25   12
12133970302      47   12
12133970303      41   13

[5075 rows x 2 columns]

In [6]:
len(datasets['FL']['Dtract'].unique())

8253

In [4]:
len(datasets['FL']['Otract'].unique())

5075

In [7]:
set(datasets['FL']['Otract'].unique()) - set(datasets['FL']['Dtract'].unique())

{np.int64(12071010107), np.int64(12083000806), np.int64(12099005943)}

In [ ]:
set(datasets['FL']['Dtract'].unique()) - set(datasets['FL']['Otract'].unique())
# len(set(datasets['FL']['Dtract'].unique()) - set(datasets['FL']['Otract'].unique()))

{np.int64(36071014400),
 np.int64(6025011201),
 np.int64(17197883402),
 np.int64(51700031500),
 np.int64(19153010707),
 np.int64(13051002900),
 np.int64(48491020310),
 np.int64(13081010201),
 np.int64(36011040800),
 np.int64(13127000101),
 np.int64(13127000103),
 np.int64(34013020200),
 np.int64(34017017900),
 np.int64(19113001005),
 np.int64(34039038000),
 np.int64(17031831600),
 np.int64(45063020601),
 np.int64(45063020605),
 np.int64(36047011901),
 np.int64(48491020352),
 np.int64(21111980100),
 np.int64(39153532999),
 np.int64(42101014600),
 np.int64(36103135303),
 np.int64(48113016903),
 np.int64(36119011401),
 np.int64(51107610702),
 np.int64(17043841102),
 np.int64(27147960400),
 np.int64(6085509201),
 np.int64(37083930702),
 np.int64(17043841111),
 np.int64(9001050200),
 np.int64(26125197400),
 np.int64(36047044700),
 np.int64(35013001309),
 np.int64(17037000800),
 np.int64(13095010401),
 np.int64(29189218401),
 np.int64(12009980000),
 np.int64(1097007204),
 np.int64(34003042400),
 np.int64(39151714400),
 np.int64(25021440101),
 np.int64(22051029100),
 np.int64(22115950701),
 np.int64(25017352300),
 np.int64(47187050604),
 np.int64(27139080304),
 np.int64(51700031602),
 np.int64(19153010804),
 np.int64(39155933301),
 np.int64(23031005301),
 np.int64(55133200500),
 np.int64(36061003900),
 np.int64(17163501700),
 np.int64(36103200901),
 np.int64(34027045000),
 np.int64(31059091600),
 np.int64(26141950100),
 np.int64(18157011100),
 np.int64(25013813404),
 np.int64(26163577000),
 np.int64(11001004201),
 np.int64(11001004202),
 np.int64(20091052201),
 np.int64(45019005100),
 np.int64(45079011501),
 np.int64(39005970600),
 np.int64(1073012910),
 np.int64(1035960500),
 np.int64(17043841204),
 np.int64(1073012916),
 np.int64(35001000117),
 np.int64(6073008312),
 np.int64(37183054007),
 np.int64(13121011901),
 np.int64(13121011902),
 np.int64(36029014207),
 np.int64(39049003200),
 np.int64(6037700801),
 np.int64(1109188800),
 np.int64(37183054018),
 np.int64(13095010500),
 np.int64(23019004100),
 np.int64(34003042500),
 np.int64(6073008324),
 np.int64(27145011400),
 np.int64(25017352400),
 np.int64(45013000400),
 np.int64(6073008339),
 np.int64(55133200600),
 np.int64(6073008346),
 np.int64(6073008350),
 np.int64(37081014501),
 np.int64(53053063401),
 np.int64(32003006700),
 np.int64(13127000303),
 np.int64(17031823605),
 np.int64(6073008373),
 np.int64(36103110902),
 np.int64(27123040503),
 np.int64(36103110901),
 np.int64(39035134203),
 np.int64(48113000704),
 np.int64(1073004800),
 np.int64(48113000706),
 np.int64(34029732101),
 np.int64(13139001607),
 np.int64(18105000201),
 np.int64(13025960202),
 np.int64(13139001611),
 np.int64(42045407502),
 np.int64(39153533200),
 np.int64(44005040400),
 np.int64(6085501200),
 np.int64(51107610900),
 np.int64(47157010710),
 np.int64(27147960600),
 np.int64(48355000602),
 np.int64(17043841308),
 np.int64(26125197600),
 np.int64(48215023907),
 np.int64(24037876003),
 np.int64(36047044902),
 np.int64(39025041702),
 np.int64(1097007400),
 np.int64(48029172008),
 np.int64(55089660202),
 np.int64(48029180202),
 np.int64(39023001900),
 np.int64(37129011503),
 np.int64(42003562800),
 np.int64(22103040304),
 np.int64(22103040306),
 np.int64(47187050802),
 np.int64(13039010100),
 np.int64(24025301301),
 np.int64(22103040308),
 np.int64(45013000503),
 np.int64(39035109701),
 np.int64(34017001800),
 np.int64(55009001801),
 np.int64(32003006800),
 np.int64(4013810000),
 np.int64(25025061203),
 np.int64(13127000405),
 np.int64(17031823703),
 np.int64(13127000408),
 np.int64(13127000409),
 np.int64(42029302103),
 np.int64(42029302104),
 np.int64(39035134300),
 np.int64(27123040606),
 np.int64(4013113702),
 np.int64(55039041902),
 np.int64(36005036400),
 np.int64(26075005301),
 np.int64(48157671800),
 np.int64(24510030200),
 np.int64(53035090300),
 np.int64(37183054206),
 np.int64(47037014400),
 np.int64(26125197702),
 np.int64(51107611015),
 np.int64(51107611020),
 np.int64(25025020301),
 np.int64(25009250700),
 np.int64(55089660303),
 np.int64(25017352600),
 np.int64(13039010201),
 np.int64(42003980700),
 np.int64(27141030302),
 np.int64(25009267103),
 np.int64(48171950500),
 np.int64(1045021102),
 np.int64(42017104303),
 np.int64(17031610800),
 np.int64(36061012400),
 np.int64(42081010100),
 np.int64(13127000501),
 np.int64(13127000503),
 np.int64(34013020600),
 np.int64(42029302203),
 np.int64(42029302204),
 np.int64(36005011900),
 np.int64(34017018302),
 np.int64(6053011902),
 np.int64(26141950400),
 np.int64(42125771200),
 np.int64(51059450300),
 np.int64(13089022404),
 np.int64(4013113800),
 np.int64(24003740106),
 np.int64(2020000206),
 np.int64(36059406801),
 np.int64(18105000401),
 np.int64(17077010900),
 np.int64(36059415000),
 np.int64(34003018200),
 np.int64(20091052506),
 np.int64(33015063001),
 np.int64(26163585500),
 np.int64(1069040100),
 np.int64(45063021035),
 np.int64(42091201005),
 np.int64(1109189101),
 np.int64(55079019000),
 np.int64(47187051001),
 np.int64(39123051000),
 np.int64(51760030200),
 np.int64(26109960700),
 np.int64(13039010302),
 np.int64(13039010303),
 np.int64(29077004804),
 np.int64(39035101700),
 np.int64(36061004300),
 np.int64(26081002000),
 np.int64(13051011600),
 np.int64(34025808402),
 np.int64(55009002003),
 np.int64(26125140500),
 np.int64(39113040405),
 np.int64(55079150100),
 np.int64(36061012500),
 np.int64(13127000601),
 np.int64(17031823903),
 np.int64(39153508900),
 np.int64(31055004200),
 np.int64(17031430700),
 np.int64(26161414700),
 np.int64(36005028400),
 np.int64(17031340600),
 np.int64(51683910201),
 np.int64(45019005500),
 np.int64(39153533501),
 np.int64(6081610302),
 np.int64(39153533502),
 np.int64(6081610304),
 np.int64(20091052604),
 np.int64(38053962302),
 np.int64(47149040200),
 np.int64(6037480011),
 np.int64(1069040204),
 np.int64(1069040205),
 np.int64(1069040206),
 np.int64(18089042508),
 np.int64(47157011020),
 np.int64(22103040602),
 np.int64(22103040607),
 np.int64(45013000800),
 np.int64(13039010403),
 np.int64(13039010404),
 np.int64(13039010405),
 np.int64(13039010407),
 np.int64(39155933800),
 np.int64(26099221100),
 np.int64(39095009902),
 np.int64(51041100403),
 np.int64(51041100406),
 np.int64(13299950200),
 np.int64(13127000702),
 np.int64(13047030402),
 np.int64(25005613700),
 np.int64(55079060101),
 np.int64(27123040901),
 np.int64(22071001736),
 np.int64(17033880200),
 np.int64(2063000200),
 np.int64(45063021204),
 np.int64(22071001751),
 np.int64(48113009303),
 np.int64(36085007001),
 np.int64(36085007002),
 np.int64(36059407000),
 np.int64(20091052701),
 np.int64(11001004702),
 np.int64(51683910302),
 np.int64(26075005602),
 np.int64(37183054502),
 np.int64(9001042600),
 np.int64(17043841704),
 np.int64(39089750700),
 np.int64(1069040301),
 np.int64(1069040302),
 np.int64(42129801901),
 np.int64(17031570100),
 np.int64(1109189300),
 np.int64(48453001912),
 np.int64(47149040312),
 np.int64(48453001916),
 np.int64(13039010500),
 np.int64(47187051204),
 np.int64(24025301703),
 np.int64(22103040711),
 np.int64(39061005000),
 np.int64(22103040712),
 np.int64(6071001803),
 np.int64(17197884103),
 np.int64(21111005901),
 np.int64(51075400400),
 np.int64(48201343700),
 np.int64(36061004500),
 np.int64(13051011800),
 np.int64(1045021400),
 np.int64(36061012700),
 np.int64(22051980000),
 np.int64(13127000800),
 np.int64(42043024101),
 np.int64(51810042600),
 np.int64(36083041000),
 np.int64(17031824106),
 np.int64(51059450601),
 np.int64(26125157100),
 np.int64(26125173500),
 np.int64(6081602300),
 np.int64(17031824129),
 np.int64(6037267201),
 np.int64(51199050500),
 np.int64(24005403401),
 np.int64(36091061002),
 np.int64(1069040400),
 np.int64(18057110301),
 np.int64(51760030501),
 np.int64(51760030502),
 np.int64(26065003301),
 np.int64(13039010603),
 np.int64(13039010604),
 np.int64(51700032300),
 np.int64(36075021104),
 np.int64(26081002300),
 np.int64(13051011900),
 np.int64(34025808701),
 np.int64(42017104703),
 np.int64(13299950400),
 np.int64(6075016000),
 np.int64(13127000900),
 np.int64(18097390405),
 np.int64(51107980100),
 np.int64(18097390407),
 np.int64(40109106000),
 np.int64(17033880400),
 np.int64(45041001300),
 np.int64(48029131609),
 np.int64(4013319001),
 np.int64(18105000802),
 np.int64(6059074405),
 np.int64(11001004902),
 np.int64(42045408103),
 np.int64(38017000300),
 np.int64(6037980013),
 np.int64(6037980016),
 np.int64(1069040500),
 np.int64(51059491705),
 np.int64(48121021305),
 np.int64(6037980028),
 np.int64(6037980030),
 np.int64(13095011200),
 np.int64(29189219200),
 np.int64(36109001600),
 np.int64(18057110405),
 np.int64(22051029900),
 np.int64(42003981200),
 np.int64(24033805201),
 np.int64(51700032400),
 np.int64(25017361300),
 np.int64(48201450402),
 np.int64(13127001001),
 np.int64(42043024300),
 np.int64(21003920300),
 np.int64(18031969200),
 np.int64(17031832500),
 np.int64(9001010101),
 np.int64(48029131700),
 np.int64(9007670200),
 np.int64(36059300800),
 np.int64(48113009604),
 np.int64(36059407301),
 np.int64(36059407302),
 np.int64(35001000906),
 np.int64(11001005003),
 np.int64(26075005900),
 np.int64(36119012303),
 np.int64(25021416400),
 np.int64(24005403602),
 np.int64(1069040600),
 np.int64(39049003000),
 np.int64(34003035100),
 np.int64(13063980000),
 np.int64(17031980000),
 np.int64(13095011300),
 np.int64(27139081200),
 np.int64(13113140210),
 np.int64(39061005301),
 np.int64(34001011704),
 np.int64(55133201402),
 np.int64(55133201404),
 np.int64(34013004802),
 np.int64(1021060101),
 np.int64(18019050504),
 np.int64(23005013002),
 np.int64(18097390602),
 np.int64(9001100300),
 np.int64(42029302802),
 np.int64(8041006100),
 np.int64(42021012500),
 np.int64(48041002006),
 np.int64(27123041302),
 np.int64(25025070104),
 np.int64(25025070102),
 np.int64(40143004700),
 np.int64(39055311900),
 np.int64(48113009701),
 np.int64(36059407402),
 np.int64(15003001901),
 np.int64(36081017902),
 np.int64(1077011504),
 np.int64(10003014706),
 np.int64(36035970100),
 np.int64(20091053109),
 np.int64(24005403703),
 np.int64(55139001400),
 np.int64(47149040702),
 np.int64(29189211202),
 np.int64(45063980100),
 np.int64(17031980100),
 np.int64(1043965001),
 np.int64(13113140303),
 np.int64(1101005904),
 np.int64(12059960401),
 np.int64(28059042900),
 np.int64(13219030104),
 np.int64(37171930202),
 np.int64(48491021402),
 np.int64(19023070300),
 np.int64(6071002204),
 np.int64(11001980000),
 np.int64(13051004001),
 np.int64(13051004002),
 np.int64(6071010402),
 np.int64(36061004900),
 np.int64(17031808100),
 np.int64(55133201505),
 np.int64(33003955301),
 np.int64(26081002600),
 np.int64(36061013100),
 np.int64(8037000302),
 np.int64(34017010800),
 np.int64(48041002100),
 np.int64(25023530100),
 np.int64(42029302902),
 np.int64(51041100922),
 np.int64(4013106300),
 np.int64(39055312000),
 np.int64(1073005701),
 np.int64(24031700105),
 np.int64(18105001101),
 np.int64(18105001102),
 np.int64(20091053201),
 np.int64(8031003801),
 np.int64(24005403802),
 np.int64(42129802400),
 np.int64(1069040801),
 np.int64(1069040802),
 np.int64(33009960102),
 np.int64(20169000102),
 np.int64(26121004200),
 np.int64(17195001000),
 np.int64(48439100602),
 np.int64(26163520700),
 np.int64(36075021504),
 np.int64(28105950401),
 np.int64(51550020809),
 np.int64(48121021643),
 np.int64(26163537100),
 np.int64(18019050703),
 np.int64(18097390801),
 np.int64(13299950802),
 np.int64(18097390802),
 np.int64(34027046104),
 np.int64(6053012700),
 np.int64(25025070302),
 np.int64(29097010400),
 np.int64(12011980000),
 np.int64(4019004642),
 np.int64(26163561700),
 np.int64(34007606500),
 np.int64(4019004648),
 np.int64(36047013100),
 np.int64(13089023214),
 np.int64(6073009400),
 np.int64(36111951100),
 np.int64(18089043203),
 np.int64(1097000200),
 np.int64(25017337101),
 np.int64(6037701902),
 np.int64(48113018130),
 np.int64(1101006100),
 np.int64(18057110807),
 np.int64(26065003802),
 np.int64(22051030300),
 np.int64(18057110813),
 np.int64(18057110815),
 np.int64(1033020705),
 np.int64(26125133102),
 np.int64(48201450804),
 np.int64(13021013302),
 np.int64(37063001400),
 np.int64(32003007802),
 np.int64(6059042109),
 np.int64(48121021759),
 np.int64(51059451200),
 np.int64(25027732801),
 np.int64(37119001922),
 np.int64(25025070402),
 np.int64(51710002500),
 np.int64(9001010500),
 np.int64(9003468102),
 np.int64(34039039302),
 np.int64(28047000900),
 np.int64(31055005000),
 np.int64(19113010500),
 np.int64(40109106503),
 np.int64(6037554511),
 np.int64(48113010001),
 np.int64(13089023315),
 np.int64(10003015000),
 np.int64(1073014104),
 np.int64(13057090908),
 np.int64(9001035101),
 np.int64(13089023327),
 np.int64(34003019104),
 np.int64(13313000801),
 np.int64(39139001700),
 np.int64(17137952100),
 np.int64(55139001700),
 np.int64(1069041000),
 np.int64(29189211500),
 np.int64(42091201902),
 np.int64(48029181303),
 np.int64(26065003901),
 np.int64(1033020802),
 np.int64(6037620102),
 np.int64(13051004300),
 np.int64(6037800336),
 np.int64(33003955601),
 np.int64(42017105300),
 np.int64(48201450900),
 np.int64(21015070102),
 np.int64(18097391001),
 np.int64(37063001501),
 np.int64(19113002400),
 np.int64(34013021601),
 np.int64(25027732901),
 np.int64(9001010600),
 np.int64(17031833000),
 np.int64(36103112104),
 np.int64(39055312300),
 np.int64(1103005101),
 np.int64(48113001901),
 np.int64(36081001903),
 np.int64(26161415600),
 np.int64(21209040303),
 np.int64(40109106608),
 np.int64(26125166000),
 np.int64(55025001901),
 np.int64(13057091001),
 np.int64(6037267901),
 np.int64(48309003709),
 np.int64(13057091010),
 np.int64(24005404102),
 np.int64(17073030600),
 np.int64(48355001802),
 np.int64(1069041100),
 np.int64(6001444301),
 np.int64(8031004110),
 np.int64(33013032400),
 np.int64(33009960402),
 np.int64(13089023444),
 np.int64(48029181402),
 np.int64(48139060702),
 np.int64(12111980000),
 np.int64(18057111011),
 np.int64(18057111012),
 np.int64(22071002600),
 np.int64(36081075701),
 np.int64(38015010300),
 np.int64(13021013502),
 np.int64(8037000702),
 np.int64(36061013502),
 np.int64(17031620100),
 np.int64(25025070600),
 np.int64(39085205002),
 np.int64(17031833100),
 np.int64(13089023501),
 np.int64(48113002001),
 np.int64(28163950100),
 np.int64(40109106708),
 np.int64(55127000600),
 np.int64(36103112218),
 np.int64(1073014301),
 np.int64(1073014303),
 np.int64(19157370400),
 np.int64(20091053603),
 np.int64(36119012900),
 np.int64(34013980200),
 np.int64(40113940014),
 np.int64(18097342000),
 np.int64(1069041200),
 np.int64(42091202100),
 np.int64(47037015613),
 np.int64(48139060802),
 np.int64(25003935300),
 np.int64(13069010500),
 np.int64(36079011400),
 np.int64(26147645000),
 np.int64(34001012302),
 np.int64(13027960400),
 np.int64(37021001300),
 np.int64(36061005400),
 np.int64(26165380700),
 np.int64(21015070301),
 np.int64(48257050204),
 np.int64(42133022300),
 np.int64(13121980000),
 np.int64(39061022302),
 np.int64(22015010400),
 np.int64(26025002600),
 np.int64(9003460202),
 np.int64(4013614700),
 np.int64(9003460204),
 np.int64(51710002800),
 np.int64(48113002100),
 np.int64(28047001205),
 np.int64(36047005302),
 np.int64(36005029500),
 np.int64(18105001600),
 np.int64(30111000200),
 np.int64(48113018506),
 np.int64(37161961102),
 np.int64(48157673109),
 np.int64(6059001507),
 np.int64(25009260200),
 np.int64(17031071400),
 np.int64(36103169706),
 np.int64(33011001000),
 np.int64(39095002800),
 np.int64(9009170100),
 np.int64(18005010100),
 np.int64(13027960500),
 np.int64(34025801400),
 np.int64(25017370302),
 np.int64(34021000900),
 np.int64(13021013701),
 np.int64(36061013700),
 np.int64(37081016011),
 np.int64(34039031500),
 np.int64(53033010900),
 np.int64(48113002200),
 np.int64(45041002204),
 np.int64(2020001500),
 np.int64(36047013600),
 np.int64(55127000801),
 np.int64(24031700706),
 np.int64(26093733603),
 np.int64(22073001700),
 np.int64(42003425000),
 np.int64(11001005802),
 np.int64(6085502704),
 np.int64(37189920500),
 np.int64(1069041400),
 np.int64(42123970300),
 np.int64(20173006600),
 np.int64(13069010701),
 np.int64(6037620501),
 np.int64(13115000600),
 np.int64(48453035800),
 np.int64(42003474202),
 np.int64(36061005600),
 np.int64(39035111202),
 np.int64(51510200102),
 np.int64(5119002407),
 np.int64(25027725100),
 np.int64(26081011502),
 np.int64(51770001200),
 np.int64(17031620400),
 np.int64(6053013300),
 np.int64(34029717300),
 np.int64(13089023802),
 np.int64(40109107002),
 np.int64(4013115200),
 np.int64(2020001602),
 np.int64(24510220100),
 np.int64(1117030216),
 np.int64(34003011400),
 np.int64(4025001804),
 np.int64(6001428301),
 np.int64(15003002701),
 np.int64(1015981901),
 np.int64(18093950800),
 np.int64(25017313101),
 np.int64(24031700818),
 np.int64(42011010903),
 np.int64(51013101401),
 np.int64(37189920602),
 np.int64(1069041500),
 np.int64(24031700829),
 np.int64(18043070302),
 np.int64(6037702501),
 np.int64(24031700838),
 np.int64(13117130601),
 np.int64(34003044202),
 np.int64(47157020532),
 np.int64(13117130615),
 np.int64(37021001602),
 np.int64(37081016201),
 np.int64(48339691403),
 np.int64(18087970700),
 np.int64(37081016204),
 np.int64(36061013900),
 np.int64(48201254800),
 np.int64(34017011600),
 np.int64(49035102100),
 np.int64(53053073301),
 np.int64(19113002900),
 np.int64(34017019800),
 np.int64(34039039900),
 np.int64(49035110300),
 np.int64(40109107101),
 np.int64(28047001503),
 np.int64(51678980000),
 np.int64(13151070114),
 np.int64(24031700901),
 np.int64(42101000101),
 np.int64(24021772200),
 np.int64(24031700904),
 np.int64(24031700905),
 np.int64(1117030315),
 np.int64(55127001000),
 np.int64(47157004200),
 np.int64(37063002030),
 np.int64(37063002037),
 np.int64(37063002038),
 np.int64(25017321400),
 np.int64(1117030330),
 np.int64(6059075516),
 np.int64(29510125500),
 np.int64(1069041600),
 np.int64(1097000901),
 np.int64(34023008206),
 np.int64(42003458001),
 np.int64(4019005400),
 np.int64(36079011801),
 np.int64(6067005403),
 np.int64(34025809901),
 np.int64(48201451501),
 np.int64(22015010801),
 np.int64(34017019900),
 np.int64(34029717501),
 np.int64(34029717502),
 np.int64(36099950600),
 np.int64(45045000200),
 np.int64(42045409300),
 np.int64(25017321500),
 np.int64(33001965598),
 np.int64(36029007904),
 np.int64(29510125600),
 np.int64(1069041700),
 np.int64(18043070500),
 np.int64(34003036200),
 np.int64(13053020201),
 np.int64(1097001001),
 np.int64(13053020205),
 np.int64(44007016500),
 np.int64(37035010102),
 np.int64(26017286200),
 np.int64(25015822402),
 np.int64(45079980100),
 np.int64(55133202500),
 np.int64(37021001802),
 np.int64(36061005900),
 np.int64(27123034201),
 np.int64(26081011801),
 np.int64(26081011803),
 np.int64(26081011804),
 np.int64(51510200409),
 np.int64(39049980000),
 np.int64(4013615202),
 np.int64(1117030502),
 np.int64(42003409001),
 np.int64(2020001900),
 np.int64(17031841900),
 np.int64(42101000300),
 np.int64(26125166700),
 np.int64(36055009402),
 np.int64(26055551100),
 np.int64(9001044100),
 np.int64(48113019013),
 np.int64(28149950600),
 np.int64(51013101705),
 np.int64(42127960200),
 np.int64(34023000200),
 np.int64(9001257100),
 np.int64(36093020300),
 np.int64(34019010701),
 np.int64(9015904400),
 np.int64(41003010200),
 np.int64(36047055000),
 np.int64(37035010204),
 np.int64(25025030302),
 np.int64(22071003301),
 np.int64(12055980200),
 np.int64(21111007400),
 np.int64(48339691700),
 np.int64(34025810102),
 np.int64(36061014200),
 np.int64(42029304000),
 np.int64(19033950402),
 np.int64(34017020100),
 np.int64(55055100100),
 np.int64(28047001800),
 np.int64(34035050703),
 np.int64(40109107407),
 np.int64(42101000401),
 np.int64(34007607504),
 np.int64(42101000403),
 np.int64(42101000404),
 np.int64(24031701205),
 np.int64(26125175000),
 np.int64(55025010905),
 np.int64(55025010908),
 np.int64(13131950300),
 np.int64(39035152605),
 np.int64(36055009500),
 np.int64(20091980001),
 np.int64(36035971300),
 np.int64(20091980005),
 np.int64(36103145701),

In [15]:
datasets['FL']

             Otract       Dtract    EST
0       12001000201  12001000201  405.0
1       12001000201  12001000202   40.0
2       12001000201  12001000301   20.0
3       12001000201  12001000400  225.0
4       12001000201  12001000500   35.0
...             ...          ...    ...
220720  12133970303  12133970103   55.0
220721  12133970303  12133970104  105.0
220722  12133970303  12133970200   15.0
220723  12133970303  12133970302   50.0
220724  12133970303  12133970303   85.0

[220725 rows x 3 columns]

In [17]:
# datasets['FL']['Otract' = np.int64(12071010107)]['EST']
datasets['FL'].loc[datasets['FL']['Otract'] == 12071010107]

            Otract       Dtract    EST
83194  12071010107   2020002301   30.0
83195  12071010107  12015010301   60.0
83196  12071010107  12015010302   10.0
83197  12071010107  12015020303    4.0
83198  12071010107  12071000600   15.0
83199  12071010107  12071000700   30.0
83200  12071010107  12071000800   20.0
83201  12071010107  12071001104   15.0
83202  12071010107  12071001203   20.0
83203  12071010107  12071001207   25.0
83204  12071010107  12071001502   65.0
83205  12071010107  12071001601    4.0
83206  12071010107  12071001602   30.0
83207  12071010107  12071001705   10.0
83208  12071010107  12071001801   15.0
83209  12071010107  12071001919    4.0
83210  12071010107  12071010108   10.0
83211  12071010107  12071010302   35.0
83212  12071010107  12071010303  110.0
83213  12071010107  12071010307   20.0
83214  12071010107  12071010309   30.0
83215  12071010107  12071010404   65.0
83216  12071010107  12071010413   20.0
83217  12071010107  12071010419    4.0
83218  12071010107  12071010420   15.0
83219  12071010107  12071010701   35.0
83220  12071010107  12071010802   75.0
83221  12071010107  12071020600  140.0
83222  12071010107  12071030100   25.0
83223  12071010107  12071040117   30.0
83224  12071010107  12071040121   20.0
83225  12071010107  12071040131   15.0
83226  12071010107  12071050106   30.0
83227  12071010107  12071050318   35.0
83228  12071010107  12071050501   45.0
83229  12071010107  12071050603    4.0
83230  12071010107  12071060101    4.0
83231  12071010107  12071060102   15.0
83232  12071010107  12071070202   15.0
83233  12071010107  12071080202   50.0
83234  12071010107  12071080300   60.0
83235  12071010107  49035114500   25.0

In [18]:
datasets['FL'].loc[datasets['FL']['Dtract'] == 12071010107]

Empty DataFrame
Columns: [Otract, Dtract, EST]
Index: []

Some census tracts are listed only as an origin and not as a destination census tract. This is interpreted as there being no commuter workers within those census tracts. Additionally, some census tracts are listed only as destinations and not as origin census tracts. This is interpreted as the resident population is 0.

We will calculate the Population of a census tract as the sum of travelers when grouped by an Otract id matching the census tract id.
The Number of Jobs held by commuters is the sum of travelers when grouped by a Dtract id matching the census tract id. For

In [25]:
fl_data = datasets['FL']

In [26]:
no_jobs = set(datasets['FL']['Otract'].unique()) - set(datasets['FL']['Dtract'].unique())

In [27]:
no_jobs = pd.DataFrame(no_jobs, columns = ['Id'])
no_jobs

            Id
0  12071010107
1  12083000806
2  12099005943

In [28]:
dtracts = datasets['FL']['Dtract'].unique()
dtracts = pd.DataFrame(dtracts, columns = ['Id'])

In [29]:
tracts = pd.concat([no_jobs, dtracts])

In [42]:
tracts.loc[tracts['Id'].isin(no_jobs['Id']), 'Jobs'] = 0

In [31]:
fl_data['Dtract'].unique()

array([12001000201, 12001000202, 12001000301, ...,  1101003301,
       12133970102,  9013881300])

In [36]:
jobs

Dtract
1003010100      10.0
1003010200      10.0
1003010400     105.0
1003010500     140.0
1003010704      20.0
               ...
55139001700      4.0
55141010400      4.0
55141011100     10.0
56005000300     10.0
56033000400     15.0
Name: EST, Length: 8253, dtype: float64

In [40]:
jobs = fl_data.groupby('Dtract')['EST'].sum()
tracts['Id'].map(jobs)

0          NaN
1          NaN
2          NaN
0       2603.0
1       1210.0
         ...
8248      45.0
8249      20.0
8250     100.0
8251      60.0
8252       4.0
Name: Id, Length: 8256, dtype: float64

In [43]:
tracts['Jobs']

0          0.0
1          0.0
2          0.0
0       2603.0
1       1210.0
         ...
8248      45.0
8249      20.0
8250     100.0
8251      60.0
8252       4.0
Name: Jobs, Length: 8256, dtype: float64

In [44]:
grouped_dsets = {}

In [45]:
for (state_code, df) in enumerate(datasets):
    grouped = pd.DataFrame()
    # no_jobs is a datafram of tracts that have a resident population, but don't provide any jobs for commuting workers from other census tracts
    no_jobs = pd.DataFrame(set(df['Otract'].unique()) - set(df['Dtract'].unique()), columns = ['Id'])
    # no_pop is a data frame of tracts that provide jobs,  but do not have any resident population
    no_pop = pd.DataFrame(set(df['Dtract'].unique()) - set(df['Otract'].unique()), columns = ['Id'])
    
    grouped['Id'] = df['Dtract'].unique()
    # now add the Ids of the census tracts that are only origin tracts and don't function as destination tract
    grouped = pd.concat([grouped, no_jobs])

    # Now add null job values to census tracts that are only origin tracts
    grouped.loc[grouped['Id'].isin(no_jobs['Id']), 'Jobs'] = 0
    # add job values to all other tracts with jobs
    jobs = df.groupby(df['Dtract'].unique())['EST'].sum()
    grouped['Id'].map(jobs)

    # Add null pop values to census tracts that are only destination tracts
    grouped.loc[grouped['Id'].isin(no_pop['Id']), 'Population'] = 0
    # add pop values to all other tracts with pop
    pop = df.groupby(df['Otract'].unique())['EST'].sum()
    grouped['Population'].map(pop)
    grouped_dsets[state_code] = grouped

TypeError: string indices must be integers

In [32]:
datasets['FL']

             Otract       Dtract    EST
0       12001000201  12001000201  405.0
1       12001000201  12001000202   40.0
2       12001000201  12001000301   20.0
3       12001000201  12001000400  225.0
4       12001000201  12001000500   35.0
...             ...          ...    ...
220720  12133970303  12133970103   55.0
220721  12133970303  12133970104  105.0
220722  12133970303  12133970200   15.0
220723  12133970303  12133970302   50.0
220724  12133970303  12133970303   85.0

[220725 rows x 3 columns]

In [ ]:
assert(datasets['AK'])

### Now add other predictors used by the traditional gravity model: :
- longitude, latitude of the centroid of each census tract

### Now add additional predictors to use:
- SVI info for each census tract
- POI_lon, POI_lat where POI is the some POI for each census tract
- POI_text which is textual data about the rating, review of the POI